// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/corda/v1/admin.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("ibc/lightclients/corda/v1/admin.proto", fileDescriptor_3cbb05eface553b8)
}

var fileDescriptor_3cbb05eface553b8 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x93, 0x46, 0x24, 0x58, 0xa5, 0x10, 0x3c, 0x61, 0x0b, 0xc1, 0x32, 0x3b, 0x9c, 0xb6,
	0x36, 0x1e, 0xd8, 0x09, 0x1e, 0x5c, 0x67, 0x97, 0xdd, 0x8c, 0x9b, 0x85, 0x4d, 0x26, 0x6c, 0x36,
	0xb9, 0xe4, 0x2d, 0x7c, 0x2c, 0xcb, 0x2b, 0x2d, 0x25, 0x79, 0x11, 0xd9, 0x0d, 0x11, 0x9b, 0x6b,
	0x87, 0xef, 0x9b, 0xf9, 0xe7, 0x4f, 0xee, 0xb5, 0x90, 0x60, 0xb4, 0x2a, 0x9d, 0x34, 0x1a, 0x6b,
	0xd7, 0x82, 0x24, 0x5b, 0xe4, 0xd0, 0x6f, 0x21, 0x2f, 0x2a, 0x5d, 0xf3, 0xc6, 0x92, 0xa3, 0xf4,
	0x46, 0x0b, 0xc9, 0xff, 0x63, 0x3c, 0x60, 0xbc, 0xdf, 0x6e, 0x6e, 0x15, 0x91, 0x32, 0x08, 0x01,
	0x14, 0xdd, 0x07, 0x60, 0xd5, 0xb8, 0x71, 0xf1, 0x1e, 0x5e, 0x93, 0xab, 0x67, 0xbf, 0xe6, 0x80,
	0xb6, 0xd7, 0x12, 0xd3, 0xa7, 0xe4, 0xf2, 0x50, 0x76, 0xae, 0xa0, 0x63, 0x9d, 0x5e, 0xf3, 0xc5,
	0xe4, 0xab, 0xc9, 0x5f, 0xbc, 0xb9, 0x39, 0x33, 0xbf, 0x8b, 0x76, 0xc7, 0xaf, 0x89, 0xc5, 0xa7,
	0x89, 0xc5, 0x3f, 0x13, 0x8b, 0x3f, 0x67, 0x16, 0x9d, 0x66, 0x16, 0x7d, 0xcf, 0x2c, 0xda, 0x25,
	0xe1, 0xca, 0xde, 0x0b, 0xfb, 0xf8, 0xfd, 0x4d, 0x69, 0x57, 0x76, 0x82, 0x4b, 0xaa, 0xa0, 0x1c,
	0x1b, 0xb4, 0x06, 0x0b, 0x85, 0x36, 0x33, 0xb9, 0x68, 0x61, 0xec, 0x74, 0x16, 0xc2, 0x67, 0xfe,
	0x75, 0x45, 0x30, 0xc0, 0x5f, 0x07, 0xd9, 0x5a, 0xc2, 0x30, 0x2c, 0x0c, 0xb8, 0xb1, 0xc1, 0x56,
	0x5c, 0x84, 0x28, 0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x14, 0x2d, 0xd3, 0x2e, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type adminServiceClient struct {
	cc grpc1.ClientConn
}

func NewAdminServiceClient(cc grpc1.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) Shutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ibc.lightclients.corda.v1.AdminService/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	Shutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) Shutdown(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}

func RegisterAdminServiceServer(s grpc1.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ibc.lightclients.corda.v1.AdminService/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Shutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.lightclients.corda.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _AdminService_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ibc/lightclients/corda/v1/admin.proto",
}
